### ISSUE TITLE
When middleware is enabled, request.current_page is not set

### ISSUE THREAD

**Issue by yakky** [aldryn/aldryn-apphook-reload#1]
If middleware is enabled, djangCMS `request.current_page` is not set for non-root views of the apphooks.
Apparently this is because at https://github.com/divio/django-cms/blob/develop/cms/appresolver.py#L41 APP_RESOLVER is not set, while it should as https://github.com/divio/django-cms/blob/develop/cms/appresolver.py#L235 gets executed before it

**Comment by stefanfoulis** [comment]
Does this only happen after reloading an apphook, or always?

**Comment by mikek** [comment]
Always for me. No matter where I put it in the list of middlewares.

**Comment by stefanfoulis** [comment]
@yakky or @mikek could you try out this? https://github.com/aldryn/aldryn-apphook-reload/pull/2
Untested, but maybe it solves theproblem.

**Comment by mikek** [comment]
Fixes the issue for me. (Note, the import path typo.)

**Comment by mikek** [comment]
@stefanfoulis, @yakky any concerns about the fix?

**Comment by stefanfoulis** [comment]
@mikek if it works well for you, I'll make a release with this fix shortly.

**Comment by yakky** [comment]
I'll test this tomorrow
@stefanfoulis if you want to release this, earlier, go ahead

**Comment by mikek** [comment]
@yakky were you able to test this, so that we ask Stefan for a release?

**Comment by yakky** [comment]
Huh, sorry, I missed this notification ... Even if I've been late to the part, it's ok to me
